# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Table_view_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Table_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(979, 814)
        Form.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.leCountry = QtWidgets.QLineEdit(Form)
        self.leCountry.setGeometry(QtCore.QRect(22, 30, 941, 41))
        self.leCountry.setObjectName("leCountry")
        self.leCountry.setPlaceholderText("   Which Country do you prefer to travel to")
        self.leCountry.setStyleSheet("QLineEdit { font-size: 20px; font-weight: bold; color: silver}")
        self.filtercombobox = QtWidgets.QComboBox(Form)
        self.filtercombobox.setGeometry(QtCore.QRect(320, 90, 341, 22))
        self.filtercombobox.setStyleSheet("font: 75 10pt \"News706 BT\";\n"
"background-color: rgb(221, 221, 221);\n"
"\n"
"border-color: rgb(255, 247, 248);")
        self.filtercombobox.setObjectName("filtercombobox")
        self.filtercombobox.addItem("")
        self.filtercombobox.addItem("")
        self.filtercombobox.addItem("")
        self.lblFilter = QtWidgets.QLabel(Form)
        self.lblFilter.setGeometry(QtCore.QRect(240, 90, 61, 21))
        self.lblFilter.setStyleSheet("border-color: rgb(255, 247, 248);")
        self.lblFilter.setObjectName("lblFilter")
        self.table = QtWidgets.QTableView(Form)
        self.table.setGeometry(QtCore.QRect(20, 130, 941, 671))
        self.table.setObjectName("table")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.filtercombobox.setToolTip(_translate("Form", "<html><head/><body><p>DEFAULT</p></body></html>"))
        self.filtercombobox.setItemText(0, _translate("Form", "Default"))
        self.filtercombobox.setItemText(1, _translate("Form", "Lowest to Highest price"))
        self.filtercombobox.setItemText(2, _translate("Form", "Highest to Lowest price"))
        self.lblFilter.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#dddddd;\">Filter</span></p></body></html>"))
